# Generated by Django 3.0.8 on 2020-07-31 10:00

from django.db import migrations, models
import django_simple_coupons.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
