# Generated by Django 3.0.8 on 2020-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0002_alter_coupon_created_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
